<?php
// JADIEL CHECK — gestor de avisos
session_start();
$dataDir=__DIR__.'/data'; if(!is_dir($dataDir)) @mkdir($dataDir,0755,true);
$file=$dataDir.'/notice.json';
// Primeiro acesso: defina uma senha forte no arquivo ou substitua por autenticação do servidor.
$adminUser='1234'; $adminPass='1234';
if(isset($_POST['logout'])){session_destroy();header('Location: gestor.php');exit;}
if(empty($_SESSION['admin'])){
 if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['login'])){if(hash_equals($adminUser,(string)($_POST['user']??''))&&hash_equals($adminPass,(string)($_POST['pass']??''))){session_regenerate_id(true);$_SESSION['admin']=true;header('Location: gestor.php');exit;}$error='Usuário ou senha inválidos.';}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gestor — JADIEL CHECK</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#050807;color:#fff;font-family:system-ui}.box{width:min(390px,88%);padding:30px;border:1px solid #5cffaa33;border-radius:24px;background:#0b1511e8;box-shadow:0 30px 100px #000}.brand{font-weight:900;font-size:22px;margin-bottom:22px}.brand span{color:#5cffaa}input,button{width:100%;height:52px;margin:7px 0;border-radius:13px;box-sizing:border-box}input{padding:0 14px;background:#ffffff08;border:1px solid #ffffff16;color:#fff}button{border:0;background:#5cffaa;font-weight:900}.err{color:#ff8585}</style></head><body><form class="box" method="post"><div class="brand">JADIEL <span>CHECK</span> · GESTOR</div><?php if(!empty($error)):?><p class="err"><?=htmlspecialchars($error)?></p><?php endif;?><input name="user" placeholder="Usuário" required><input name="pass" type="password" placeholder="Senha" required><button name="login">ENTRAR</button></form></body></html><?php exit; }
$notice=[]; if(is_file($file)){$notice=json_decode(@file_get_contents($file),true)?:[];}
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['save_notice'])){$title=trim($_POST['title']??'');$message=trim($_POST['message']??'');$expires=trim($_POST['expires_at']??'');$notice=['active'=>true,'title'=>$title?:'Aviso','message'=>$message,'expires_at'=>$expires?:null,'updated_at'=>date('c')];file_put_contents($file,json_encode($notice,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX);header('Location: gestor.php?saved=1');exit;}
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['delete_notice'])){$notice=['active'=>false];file_put_contents($file,json_encode($notice,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),LOCK_EX);header('Location: gestor.php?deleted=1');exit;}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gestor — JADIEL CHECK</title><style>:root{--g:#5cffaa}*{box-sizing:border-box}body{margin:0;background:#050807;color:#f5fff9;font-family:system-ui}.wrap{width:min(900px,92%);margin:auto}.top{display:flex;justify-content:space-between;align-items:center;padding:25px 0}.brand{font-weight:900;font-size:22px}.brand span{color:var(--g)}button{border:0;border-radius:13px;padding:13px 18px;font-weight:800;cursor:pointer}.logout{background:#ffffff10;color:#fff}.card{padding:25px;border:1px solid #5cffaa25;border-radius:24px;background:#0b1511e8;box-shadow:0 20px 70px #0006;margin-bottom:20px}label{display:block;margin:15px 0 7px;color:#a6b9ae}input,textarea{width:100%;border-radius:13px;border:1px solid #ffffff15;background:#ffffff08;color:#fff;padding:14px;font:inherit}textarea{min-height:150px;resize:vertical}.save{margin-top:18px;background:var(--g);color:#03130b}.delete{margin-top:18px;background:#ff5c6c;color:#260306}.status{padding:12px;border-radius:12px;background:#5cffaa12;color:#9fffc8}</style></head><body><div class="wrap"><header class="top"><div class="brand">JADIEL <span>CHECK</span> · GESTOR</div><form method="post"><button class="logout" name="logout">Sair</button></form></header><?php if(isset($_GET['saved'])):?><div class="status">Aviso publicado. O botão de aviso aparece no site enquanto o aviso estiver ativo.</div><?php elseif(isset($_GET['deleted'])):?><div class="status">Aviso removido. O botão de aviso desaparece do site.</div><?php endif;?><section class="card"><h1>Controle de aviso</h1><p>Crie, edite, expire ou remova o aviso exibido no index.php.</p><form method="post"><label>Título</label><input name="title" value="<?=htmlspecialchars($notice['title']??'')?>" placeholder="Título do aviso"><label>Mensagem</label><textarea name="message" placeholder="Escreva o aviso..."><?=htmlspecialchars($notice['message']??'')?></textarea><label>Expira em</label><input type="datetime-local" name="expires_at" value="<?=htmlspecialchars(!empty($notice['expires_at'])?date('Y-m-d\TH:i',strtotime($notice['expires_at'])):'')?>"><button class="save" name="save_notice">PUBLICAR AVISO</button></form><form method="post"><button class="delete" name="delete_notice">APAGAR AVISO</button></form></section></div></body></html>
