<?php declare(strict_types=1); ?>
<!doctype html><html lang="pt-BR"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#05080d">
<title>JADIEL AI</title>
<style>
:root{--bg:#05080d;--panel:#0b141dcc;--line:#69e7ff22;--cyan:#69e7ff;--text:#edfaff;--muted:#7894a5}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:radial-gradient(circle at 50% 35%,#0e2937,#071018 35%,#05080d 70%);color:var(--text);font-family:Inter,system-ui,sans-serif}body{overflow:hidden}.app{min-height:100vh;display:flex;flex-direction:column}.top{z-index:3;display:flex;justify-content:space-between;padding:18px 22px}.brand{font-weight:800;letter-spacing:.18em}.status{font-size:11px;color:var(--muted)}.status i{display:inline-block;width:7px;height:7px;border-radius:50%;background:#43e6a3;box-shadow:0 0 12px #43e6a3;margin-right:7px}.main{z-index:2;flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center}.orb-wrap{width:min(58vw,390px);aspect-ratio:1;display:grid;place-items:center}.orb{width:58%;height:58%;border-radius:50%;background:radial-gradient(circle at 35% 28%,#fff 0,#79ebff 8%,#168dbb 27%,#073d59 53%,#03131f 74%,transparent 76%);box-shadow:0 0 30px #4adfff66,0 0 100px #14baff33,inset 0 0 40px #b8f8ff55;position:relative;animation:breathe 3s infinite}.orb:before,.orb:after{content:"";position:absolute;inset:-17%;border:1px solid #5ce5ff55;border-radius:50%;transform:rotate(25deg) scaleY(.42);animation:spin 8s linear infinite}.orb:after{inset:-26%;transform:rotate(-30deg) scaleY(.25);animation-duration:11s}.speaking{animation:breathe .65s infinite;box-shadow:0 0 50px #69e7ffaa,0 0 140px #20b8ff55}@keyframes breathe{50%{transform:scale(1.06)}}@keyframes spin{to{transform:rotate(385deg) scaleY(.42)}}.hint{color:var(--muted);font-size:12px;margin:4px 0 18px}.answer{width:min(820px,94vw);max-height:26vh;overflow:auto;text-align:center;font-size:clamp(16px,2vw,20px);line-height:1.55;padding:8px 18px}.answer:empty:after{content:"Fale comigo ou digite uma pergunta";color:#526c7b}.controls{z-index:4;width:min(820px,94vw);display:flex;gap:10px;margin:12px auto 24px}.input{flex:1;display:flex;align-items:center;background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:7px 8px;backdrop-filter:blur(16px)}input{flex:1;background:none;border:0;outline:0;color:var(--text);font-size:15px;padding:12px}.input button,.mic{width:44px;height:44px;border:1px solid #6deaff33;background:#0b1822;border-radius:14px;color:#c9f8ff;cursor:pointer}.mic{border-radius:50%;font-size:17px}.active{box-shadow:0 0 25px #2bd4ff66}.footer{z-index:3;text-align:center;color:#476273;font-size:10px;padding-bottom:12px}.error{color:#ff9d9d}@media(max-width:600px){.orb-wrap{width:76vw}.top{padding:15px}}
</style></head><body><div class="app"><canvas id="p"></canvas><header class="top"><div class="brand">JADIEL AI</div><div class="status"><i></i><span id="st">ONLINE</span></div></header>
<main class="main"><div class="orb-wrap"><div class="orb" id="orb"></div></div><div class="hint">ASSISTENTE INTELIGENTE • GEMINI</div><div class="answer" id="ans"></div></main>
<div class="controls"><button class="mic" id="mic" aria-label="Microfone">●</button><form class="input" id="form"><input id="q" placeholder="Digite sua pergunta..." autocomplete="off"><button>➤</button></form></div><footer class="footer">Gemini • Voz do navegador</footer></div>
<script>
const orb=document.querySelector('#orb'),ans=document.querySelector('#ans'),q=document.querySelector('#q'),st=document.querySelector('#st'),mic=document.querySelector('#mic');let hist=[];
function speak(t){if(!speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='pt-BR';u.rate=.9;u.pitch=.72;let v=speechSynthesis.getVoices().find(x=>/^pt-BR/i.test(x.lang))||speechSynthesis.getVoices().find(x=>/^pt/i.test(x.lang));if(v)u.voice=v;u.onstart=()=>orb.classList.add('speaking');u.onend=()=>orb.classList.remove('speaking');speechSynthesis.speak(u)}
async function ask(t){t=t.trim();if(!t)return;q.value='';ans.textContent='';st.textContent='PROCESSANDO';try{let r=await fetch('api/chat.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:t,history:hist})}),d=await r.json();if(!r.ok)throw Error(d.error||'Erro');hist.push({role:'user',text:t},{role:'model',text:d.reply});hist=hist.slice(-12);ans.textContent=d.reply;st.textContent='ONLINE';speak(d.reply)}catch(e){ans.textContent=e.message;st.textContent='ERRO'}}
document.querySelector('#form').onsubmit=e=>{e.preventDefault();ask(q.value)};const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){let r=new SR();r.lang='pt-BR';r.onstart=()=>{mic.classList.add('active');st.textContent='OUVINDO'};r.onend=()=>{mic.classList.remove('active');st.textContent='ONLINE'};r.onresult=e=>ask(e.results[0][0].transcript);mic.onclick=()=>{try{r.start()}catch(e){}}}else mic.style.display='none';
const c=document.querySelector('#p'),x=c.getContext('2d');let ps=[];function size(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ps=Array.from({length:Math.min(130,innerWidth/8)},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.4+.2,v:(Math.random()-.5)*.2}))}function loop(){x.clearRect(0,0,innerWidth,innerHeight);ps.forEach(a=>{a.y+=a.v;if(a.y<0)a.y=innerHeight;if(a.y>innerHeight)a.y=0;x.beginPath();x.arc(a.x,a.y,a.r,0,7);x.fillStyle='rgba(105,231,255,.42)';x.fill()});requestAnimationFrame(loop)}onresize=size;size();loop();
</script></body></html>